name: Release

on:
  push:
    branches:
      - master

env:
  HUSKY: 0

jobs:
  check:
    name: Check
    uses: ./.github/workflows/check.yaml
    secrets: inherit

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - check
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          registry-url: https://npm.pkg.github.com
          node-version: 18
          cache: npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.FINANDO_GITHUB_BOT_TOKEN }}

      - name: Install dependencies
        run: npm ci --quiet --ignore-scripts

      - name: Count changed packages
        id: changes
        run: echo "count=$(npx lerna changed -a -p | wc -l | xargs)" >> "$GITHUB_OUTPUT"

      - name: Import GPG key for Finando GitHub Bot
        id: gpg
        uses: crazy-max/ghaction-import-gpg@v6
        if: ${{ fromJson(steps.changes.outputs.count) > 0 }}
        with:
          gpg_private_key: ${{ secrets.FINANDO_GITHUB_BOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.FINANDO_GITHUB_BOT_GPG_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true

      - name: Release affected packages
        if: ${{ fromJson(steps.changes.outputs.count) > 0 }}
        run: npx lerna version --yes
        env:
          GH_TOKEN: ${{ secrets.FINANDO_GITHUB_BOT_TOKEN }}
