name: Release packages

on:
  push:
    branches:
      - master

jobs:
  checks:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci --quiet --ignore-scripts

      - name: Audit dependencies
        run: npm audit --omit=dev --audit-level=moderate

      - name: Lint project
        run: npm run lint

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - checks
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci --quiet --ignore-scripts

      - name: Import GPG key for Finando GitHub Bot
        id: gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.FINANDO_GITHUB_BOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.FINANDO_GITHUB_BOT_GPG_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: false # https://github.com/semantic-release/semantic-release/pull/1871

      - name: Release affected packages
        run: npx lerna version --yes
        env:
          GH_TOKEN: ${{ secrets.FINANDO_GITHUB_BOT_TOKEN }}
